[tox]
envlist = py312

[testenv:build]
deps = -r requirements.txt
commands =
    python build_test.py

[testenv:package]
deps = -r requirements.txt
commands =
    python -c "import shutil; shutil.copytree('src', 'build', ignore=shutil.ignore_patterns('__pycache__')); shutil.make_archive('lambda/server-management-incident-handler', 'zip', 'build'); shutil.rmtree('build')"

[testenv:format]
deps =
    black
commands =
    black .

[testenv:style-check]
deps =
    black
commands =
    black --check .